export enum AuthStatesConstants {
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
    WRONG_CREDENTIALS_USER_NOT_FOUND = "WRONG_CREDENTIALS_USER_NOT_FOUND",
    WRONG_CREDENTIALS_INVALID_PASSWORD = "WRONG_CREDENTIALS_INVALID_PASSWORD",
    ACCOUNT_NOT_ACTIVATED = "ACCOUNT_NOT_ACTIVATED" ,
    USER_WITH_SAME_USERNAME_EXISTS = "USER_WITH_SAME_USERNAME_EXISTS",
    USER_WITH_SAME_EMAIL_EXISTS = "USER_WITH_SAME_EMAIL_EXISTS",
    ERROR_WHILE_SENDING_EMAIL_USER_NOT_FOUND = "ERROR_WHILE_SENDING_EMAIL_USER_NOT_FOUND"
}