export enum ForgotPasswordFormStates {
    FORGOT_NEW_PASSWORD_FORM = "FORGOT_NEW_PASSWORD_FORM",
    FORGOT_PASSWORD_EMAIL_FORM = "FORGOT_PASSWORD_EMAIL_FORM",
    FORGOT_PASSWORD_TOKEN_STATUS = "FORGOT_PASSWORD_TOKEN_STATUS"
}